version: '2.1'

services:

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.7.0
    container_name: nginx-exporter
    restart: unless-stopped
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    ports:
      - "9113:9113"
    networks:
      - nginx-status
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "3" 

networks:
  nginx-status:
    external: true