version: '3.7'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - /opt/docker_volumes/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./services/.env.db
    networks:
      - web-network
    restart: always 
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./services/.env.web
    networks:
      web-network:
          aliases:
              - web     
    depends_on:
      - db
    restart: always 
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    networks:
      - web-network
      - nginx-status
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:

networks:
    web-network:
    nginx-status:
      external: true